use vars and secrets

diff --git a/.github/workflows/reusable-extension-ci.yml b/.github/workflows/reusable-extension-ci.yml
--- a/.github/workflows/reusable-extension-ci.yml
+++ b/.github/workflows/reusable-extension-ci.yml
@@ -37,27 +37,6 @@ on:
         default: false
         description: |
           Can be used for private repos. The helm chart will be uploaded to the gh-pages branch
-      gcp_project_id:
-        type: string
-        required: false
-        description: |
-          The gcp project of artifact registries
-      gcp_project_sa:
-        type: string
-        required: false
-        description: |
-          The gcp project service account of artifact registries
-      gcp_project_location:
-        type: string
-        required: false
-        default: europe-west1
-        description: |
-          The gcp location of artifact registries
-      gcp_workload_identity_provider:
-        type: string
-        required: false
-        description: |
-          The gcp workload identity provider for artifact registries
       gcp_deb_dev_artifact_registry:
         type: string
         required: false
@@ -116,6 +95,9 @@ on:
       VERSION_BUMPER_SECRET:
         required: false
         description: Private key of the github app to use for version bump
+      GCP_ARTIFACT_REGISTRY_IDENTITY_PROVIDER:
+        required: false
+        description: Identity provider to use to be able to push to gcp artifact registry
 
 jobs:
   audit:
@@ -364,9 +346,9 @@ jobs:
         uses: 'google-github-actions/auth@v2'
         with:
           token_format: 'access_token'
-          project_id: ${{ inputs.gcp_project_id }}
-          service_account: ${{ inputs.gcp_project_sa }}
-          workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
+          project_id: ${{ vars.GCP_ARTIFACT_REGISTRY_PROJECT_ID }}
+          service_account: ${{ vars.inputs.GCP_ARTIFACT_REGISTRY_PROJECT_SA }}
+          workload_identity_provider: ${{ secrets.GCP_ARTIFACT_REGISTRY_IDENTITY_PROVIDER }}
 
 
       - name: "[build] Upload packages to gcp internal repositories"
@@ -374,7 +356,7 @@ jobs:
         working-directory: ./dist
         run: |
           for deb in $(find * -name '*.deb'); do
-            ERROR=$(gcloud artifacts apt upload ${{ inputs.gcp_deb_dev_artifact_registry }} --location=${{ inputs.gcp_project_location }} --source=$deb 2>&1) || {
+            ERROR=$(gcloud artifacts apt upload ${{ inputs.gcp_deb_dev_artifact_registry }} --location=${{ vars.GCP_ARTIFACT_REGISTRY_PROJECT_LOCATION }} --source=$deb 2>&1) || {
               echo "$ERROR"
               if echo "$ERROR" | grep -q 'updated packages must bear a new version'; then
                 echo "The package is already uploaded. Continuing..."
@@ -385,7 +367,7 @@ jobs:
             }
           done
           for rpm in $(find * -name '*.rpm'); do
-            ERROR=$(gcloud artifacts yum upload ${{ inputs.gcp_yum_dev_artifact_registry }} --location=${{ inputs.gcp_project_location }} --source=$rpm 2>&1) || {
+            ERROR=$(gcloud artifacts yum upload ${{ inputs.gcp_yum_dev_artifact_registry }} --location=${{ vars.GCP_ARTIFACT_REGISTRY_PROJECT_LOCATION }} --source=$rpm 2>&1) || {
               echo "$ERROR"
               if echo "$ERROR" | grep -q 'updated packages must bear a new version'; then
                 echo "The package is already uploaded. Continuing..."
@@ -395,6 +377,32 @@ jobs:
               fi
             }
           done
+
+      - name: "[release] Upload packages to gcp public repositories"
+        if: ${{ startsWith(github.ref, 'refs/tags/') }}
+        run: |
+          for deb in $(find * -name '*.deb'); do
+            ERROR=$(gcloud artifacts apt upload ${{ inputs.gcp_deb_public_artifact_registry }} --location=${{ vars.GCP_ARTIFACT_REGISTRY_PROJECT_LOCATION }} --source=$deb 2>&1) || {
+              echo "$ERROR"
+              if echo "$ERROR" | grep -q 'updated packages must bear a new version'; then
+                echo "The package is already uploaded. Continuing..."
+              else
+                echo "Package installation failed for a different reason."
+                exit 1
+              fi
+            }
+          done
+          for rpm in $(find * -name '*.rpm'); do
+            ERROR=$(gcloud artifacts yum upload ${{ inputs.gcp_yum_public_artifact_registry }} --location=${{ vars.GCP_ARTIFACT_REGISTRY_PROJECT_LOCATION }} --source=$rpm 2>&1) || {
+              echo "$ERROR"
+              if echo "$ERROR" | grep -q 'updated packages must bear a new version'; then
+                echo "The package is already uploaded. Continuing..."
+              else
+                echo "Package installation failed for a different reason."
+                exit 1
+              fi
+            }
+          done 
 
   test-helm-charts:
     name: "Test Helm Charts"
